import {useEffect,useState} from "react";
import {Check,Clock3,Package,Trash2,X} from "lucide-react";
import type {Profile} from "../types";
import {supabase} from "../lib/supabase";
type Item={item_name:string;quantity:number;size:string|null;unit_price:number;line_total:number;catalog_items?:{image_path:string|null;description:string}|null};
type Order={id:string;category:string;employee_name:string|null;store_name:string|null;total:number;decision:string|null;decision_notes:string|null;created_at:string;responsibility:string;payroll_acknowledged:boolean;notes:string|null;profiles?:{full_name:string}|null;portal_order_items?:Item[]};
export default function Approvals({profile}:{profile:Profile}){
 const[orders,setOrders]=useState<Order[]>([]),[selected,setSelected]=useState<Order|null>(null),[decision,setDecision]=useState("approved"),[note,setNote]=useState(""),[message,setMessage]=useState("");
 const canReview=profile.role==="supervisor"||profile.role==="accounting"||profile.role==="admin";
 const load=async()=>{if(!supabase)return;const{data,error}=await supabase.from("portal_orders").select("id,category,employee_name,store_name,total,decision,decision_notes,created_at,responsibility,payroll_acknowledged,notes,profiles!portal_orders_ordered_by_fkey(full_name),portal_order_items(item_name,quantity,size,unit_price,line_total,catalog_items(image_path,description))").order("created_at",{ascending:false});if(error)setMessage(error.message);else setOrders((data??[])as any)};
 useEffect(()=>{load()},[]);
 const imageUrl=(path:string|null|undefined)=>path&&supabase?supabase.storage.from("catalog-images").getPublicUrl(path).data.publicUrl:null;
 const save=async()=>{if(!supabase||!selected)return;const{error}=await supabase.from("portal_orders").update({decision,decision_notes:note,status:decision==="approved"?"approved":"returned",decided_by:profile.id,decided_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",selected.id);if(error){setMessage(error.message);return}setSelected(null);setNote("");setMessage("Decision saved and visible to the submitter.");load()};
 const canDelete=profile.role==="admin"||profile.role==="accounting";
 const remove=async()=>{if(!supabase||!selected||!canDelete)return;if(!window.confirm("Permanently delete this order request? This cannot be undone."))return;const{error}=await supabase.from("portal_orders").delete().eq("id",selected.id);if(error){setMessage(error.message);return}setSelected(null);setNote("");setMessage("Order request deleted.");load()};
 const open=(x:Order)=>{setSelected(x);setDecision(x.decision??"approved");setNote(x.decision_notes??"")},pending=orders.filter(x=>!x.decision).length;
 return <div className="page"><div className="page-heading"><p className="eyebrow">{canReview?"Order review":"Submission history"}</p><h1>{canReview?"Approvals and order history.":"My submitted orders."}</h1><p>{canReview?"Open an order for its full purchasing and payroll details.":"Review the orders you submitted and follow their approval status."}</p></div><div className="queue-summary"><div><Clock3/><b>{pending} waiting</b></div><div><Check/><b>{orders.length-pending} decided</b></div></div>{message&&<p className="inline-message">{message}</p>}<section className="approval-list">{orders.map(x=><article className="approval-card" key={x.id}><span className="approval-icon"><Package/></span><div className="approval-copy"><p className="eyebrow">{x.category} · {x.store_name}</p><h2>{x.employee_name||x.profiles?.full_name||"Store purchase"}</h2><p>{x.portal_order_items?.reduce((n,i)=>n+i.quantity,0)} total item(s) · ${Number(x.total).toFixed(2)}</p><time>{new Date(x.created_at).toLocaleString()}</time></div><div className="approval-actions"><span className={`decision-pill ${x.decision??"pending"}`}>{(x.decision??"pending").replaceAll("_"," ")}</span><button className="button secondary" onClick={()=>open(x)}>View full order</button></div></article>)}</section>
 {selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><section className="order-detail-modal" onClick={e=>e.stopPropagation()}><button className="icon-button modal-close" onClick={()=>setSelected(null)}><X/></button><div className="order-detail-heading"><div><p className="eyebrow">{selected.category} order</p><h2>{selected.employee_name||"Store purchase"}</h2><p>{selected.store_name} · Submitted by {selected.profiles?.full_name} · {new Date(selected.created_at).toLocaleString()}</p></div><div className={`payment-badge ${selected.responsibility}`}>{selected.responsibility==="employee_deduction"?<><strong>Employee payroll deduction</strong><span>{selected.payroll_acknowledged?"Acknowledgment completed":"Acknowledgment missing"}</span></>:<><strong>Store-paid order</strong><span>No payroll deduction</span></>}</div></div>
 <div className="responsive-table order-table"><table><thead><tr><th>Item</th><th>Size</th><th>Quantity</th><th>Unit price</th><th>Total</th></tr></thead><tbody>{selected.portal_order_items?.map((i,n)=>{const url=imageUrl(i.catalog_items?.image_path);return <tr key={`${i.item_name}-${i.size}-${n}`}><td><div className="order-product">{url?<img src={url} alt=""/>:<span><Package/></span>}<div><strong>{i.item_name}</strong><small>{i.catalog_items?.description}</small></div></div></td><td><strong>{i.size||"Standard"}</strong></td><td>{i.quantity}</td><td>${Number(i.unit_price).toFixed(2)}</td><td><strong>${Number(i.line_total).toFixed(2)}</strong></td></tr>})}</tbody><tfoot><tr><td colSpan={4}>Order total</td><td><strong>${Number(selected.total).toFixed(2)}</strong></td></tr></tfoot></table></div>{selected.notes&&<div className="order-notes"><strong>Submitter notes</strong><p>{selected.notes}</p></div>}
 {canReview?<div className="decision-form"><label>Decision<select value={decision} onChange={e=>setDecision(e.target.value)}><option value="approved">Approved</option><option value="denied">Denied</option><option value="partially_approved">Partially approved</option></select></label><label>Reviewer notes<textarea rows={4} value={note} onChange={e=>setNote(e.target.value)} placeholder="For partial approvals, specify exactly what should be ordered."/></label><button className="button primary" onClick={save}>Save decision</button></div>:<div className="decision-readonly"><strong>Status: {(selected.decision??"pending").replaceAll("_"," ")}</strong><p>{selected.decision_notes||"No reviewer notes have been added."}</p></div>}{canDelete&&<div className="request-admin-actions"><button className="button secondary danger" onClick={remove}><Trash2 size={17}/> Delete request</button></div>}</section></div>}</div>;
}
