import { FormEvent, useEffect, useState } from "react";
import { ImagePlus, Package, Pencil, Plus } from "lucide-react";
import { supabase } from "../lib/supabase";
import type { CatalogCategory, CatalogItem, Profile } from "../types";

const blank = {name:"",description:"",price:"",sizes:"S, M, L, XL",category:"uniform" as CatalogCategory,active:true};
export default function CatalogAdmin({profile}:{profile:Profile}) {
  const [items,setItems]=useState<CatalogItem[]>([]), [form,setForm]=useState(blank), [editing,setEditing]=useState<string|null>(null), [file,setFile]=useState<File|null>(null), [message,setMessage]=useState("");
  const [receiptCategories,setReceiptCategories]=useState<{id:string;name:string;active:boolean}[]>([]),[newReceiptCategory,setNewReceiptCategory]=useState("");
  const load=()=>supabase?.from("catalog_items").select("*").order("category").order("name").then(({data})=>setItems((data??[]).map((x:any)=>({id:x.id,category:x.category,name:x.name,description:x.description,price:Number(x.price),imagePath:x.image_path,imageUrl:x.image_path?supabase!.storage.from("catalog-images").getPublicUrl(x.image_path).data.publicUrl:null,sizes:x.sizes??[],active:x.active}))));
  useEffect(()=>{load()},[]);
  const loadReceiptCategories=()=>supabase?.from("receipt_categories").select("id,name,active").order("name").then(({data})=>setReceiptCategories(data??[]));
  useEffect(()=>{loadReceiptCategories()},[]);
  const addReceiptCategory=async()=>{if(!supabase||!newReceiptCategory.trim())return;const{error}=await supabase.from("receipt_categories").insert({name:newReceiptCategory.trim()});if(error)setMessage(error.message);else{setNewReceiptCategory("");loadReceiptCategories()}};
  const renameReceiptCategory=async(x:{id:string;name:string})=>{const name=window.prompt("Receipt category name",x.name)?.trim();if(!name||!supabase)return;const{error}=await supabase.from("receipt_categories").update({name,updated_at:new Date().toISOString()}).eq("id",x.id);if(error)setMessage(error.message);else loadReceiptCategories()};
  const toggleReceiptCategory=async(x:{id:string;active:boolean})=>{if(!supabase)return;const{error}=await supabase.from("receipt_categories").update({active:!x.active,updated_at:new Date().toISOString()}).eq("id",x.id);if(error)setMessage(error.message);else loadReceiptCategories()};
  const edit=(x:CatalogItem)=>{setEditing(x.id);setForm({name:x.name,description:x.description,price:String(x.price),sizes:x.sizes.join(", "),category:x.category,active:x.active});window.scrollTo({top:0,behavior:"smooth"})};
  const save=async(e:FormEvent)=>{e.preventDefault();if(!supabase)return;setMessage("Saving…");let imagePath=items.find(x=>x.id===editing)?.imagePath??null;if(file){imagePath=`${crypto.randomUUID()}-${file.name.replace(/[^a-z0-9.]/gi,"-")}`;const {error}=await supabase.storage.from("catalog-images").upload(imagePath,file,{upsert:false});if(error){setMessage(`Picture upload failed: ${error.message}`);return;}}
    const payload={name:form.name,description:form.description,price:Number(form.price),sizes:form.sizes.split(",").map(x=>x.trim()).filter(Boolean),category:form.category,active:form.active,image_path:imagePath,created_by:profile.id,updated_at:new Date().toISOString()};
    const result=editing?await supabase.from("catalog_items").update(payload).eq("id",editing):await supabase.from("catalog_items").insert(payload);if(result.error){setMessage(`Product save failed: ${result.error.message}`);return;}setForm(blank);setEditing(null);setFile(null);setMessage("Product saved.");load();};
  return <div className="page"><div className="page-heading"><p className="eyebrow">Admin control panel</p><h1>Catalog management.</h1><p>Control uniform and smallwares pricing, photos, descriptions, sizes, and availability.</p></div>
    <form className="panel catalog-editor" onSubmit={save}><div className="form-grid"><label>Catalog<select value={form.category} onChange={e=>setForm({...form,category:e.target.value as CatalogCategory})}><option value="uniform">Uniforms</option><option value="smallware">Smallwares</option></select></label><label>Product name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Price<input required min="0" step="0.01" type="number" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label><label>Sizes (comma separated)<input value={form.sizes} onChange={e=>setForm({...form,sizes:e.target.value})} placeholder="Leave blank if not applicable"/></label></div><label>Description<textarea required rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label className="file-field"><ImagePlus/> Product picture<input type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0]??null)}/></label><label className="check-row"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/><span>Available for ordering</span></label><div className="button-row"><button className="button primary">{editing?"Update product":"Add product"}</button>{editing&&<button type="button" className="button secondary" onClick={()=>{setEditing(null);setForm(blank)}}>Cancel</button>}</div>{message&&<p className="inline-message">{message}</p>}</form>
    <section className="panel catalog-admin-list"><h2>Current products</h2>{items.map(x=><article key={x.id}><div className="catalog-thumb">{x.imageUrl?<img src={x.imageUrl} alt=""/>:<Package/>}</div><div><strong>{x.name}</strong><small>{x.category} · ${x.price.toFixed(2)} · {x.active?"Active":"Hidden"}</small></div><button className="button secondary" onClick={()=>edit(x)}><Pencil size={15}/> Edit</button></article>)}</section>
    <section className="panel receipt-category-admin"><div><p className="eyebrow">Accounting settings</p><h2>Receipt categories</h2><p>These options appear on every receipt submission.</p></div><div className="category-add"><input value={newReceiptCategory} onChange={e=>setNewReceiptCategory(e.target.value)} placeholder="New receipt category"/><button className="button secondary" onClick={addReceiptCategory}><Plus/> Add category</button></div><div className="category-list">{receiptCategories.map(x=><div key={x.id} className={!x.active?"inactive":""}><strong>{x.name}</strong><span>{x.active?"Active":"Hidden"}</span><button className="text-button" onClick={()=>renameReceiptCategory(x)}>Rename</button><button className="text-button" onClick={()=>toggleReceiptCategory(x)}>{x.active?"Hide":"Restore"}</button></div>)}</div></section></div>;
}
