import { useEffect, useMemo, useState } from "react";
import { AlertCircle, CheckCircle2, Eye, Search, X } from "lucide-react";
import { supabase } from "../lib/supabase";

type Transaction={id:string;purchaseDate:string;person:string;vendor:string;amount:number;status:string;category:string;purpose:string;storagePath:string;reviewNotes:string;acknowledgedAt:string|null};
export default function Reconciliation(){
  const today=new Date().toISOString().slice(0,10), start=new Date(Date.now()-30*86400000).toISOString().slice(0,10);
  const [from,setFrom]=useState(start),[to,setTo]=useState(today),[transactions,setTransactions]=useState<Transaction[]>([]),[search,setSearch]=useState(""),[selected,setSelected]=useState<Transaction|null>(null),[fileUrl,setFileUrl]=useState(""),[message,setMessage]=useState(""),[reviewNotes,setReviewNotes]=useState("");
  const load=async()=>{if(!supabase)return;setMessage("Loading…");const {data,error}=await supabase.from("card_receipts").select("id,purchase_date,vendor,amount,status,category,business_purpose,storage_path,review_notes,acknowledged_at,profiles!card_receipts_employee_id_fkey(full_name)").gte("purchase_date",from).lte("purchase_date",to).order("purchase_date",{ascending:false});if(error){setMessage(error.message);return;}setTransactions((data??[]).map((x:any)=>({id:x.id,purchaseDate:x.purchase_date,person:x.profiles?.full_name??"Team member",vendor:x.vendor,amount:Number(x.amount),status:x.status,category:x.category,purpose:x.business_purpose,storagePath:x.storage_path,reviewNotes:x.review_notes??"",acknowledgedAt:x.acknowledged_at})));setMessage("")};
  useEffect(()=>{load()},[]);
  const view=async(x:Transaction)=>{setSelected(x);setReviewNotes(x.reviewNotes);setFileUrl("");if(supabase){const {data}=await supabase.storage.from("receipts").createSignedUrl(x.storagePath,900);setFileUrl(data?.signedUrl??"")}};
  const decide=async(status:"needs_review"|"matched"|"rejected")=>{if(!supabase||!selected)return;const {data:userData}=await supabase.auth.getUser(),now=new Date().toISOString();const patch:any={status,review_notes:reviewNotes,reviewed_by:userData.user?.id??null,reviewed_at:now,updated_at:now};if(!selected.acknowledgedAt){patch.acknowledged_at=now;patch.acknowledged_by=userData.user?.id??null}const {error}=await supabase.from("card_receipts").update(patch).eq("id",selected.id);if(error){setMessage(error.message);return}setSelected(null);setMessage(status==="matched"?"Receipt approved.":status==="rejected"?"Receipt rejected.":"Receipt acknowledged.");load()};
  const filtered=useMemo(()=>transactions.filter(x=>`${x.person} ${x.vendor} ${x.amount} ${x.category} ${x.purpose}`.toLowerCase().includes(search.toLowerCase())),[transactions,search]);
  const total=transactions.reduce((s,x)=>s+x.amount,0), matched=transactions.filter(x=>x.status==="matched").length;
  return <div className="page"><div className="page-heading"><p className="eyebrow">Accounting</p><h1>Receipt review.</h1><p>Choose any date range, review every entry, and open the attached receipt.</p></div>
    <section className="panel receipt-filters"><label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Through<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button className="button primary" onClick={load}>Apply dates</button><label className="search-field"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search entries"/></label></section>
    <div className="metric-grid"><div className="metric-card"><span>Selected period</span><strong>${total.toFixed(2)}</strong><small>{transactions.length} transactions</small></div><div className="metric-card"><span>Matched</span><strong>{matched}</strong><small>Reviewed receipts</small></div><div className="metric-card attention"><span>Needs review</span><strong>{transactions.length-matched}</strong><small>Open entries</small></div></div>{message&&<p className="inline-message">{message}</p>}
    <section className="panel table-panel"><div className="responsive-table"><table><thead><tr><th>Date</th><th>Employee</th><th>Vendor</th><th>Category</th><th>Amount</th><th>Status</th><th></th></tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td>{new Date(x.purchaseDate+"T12:00:00").toLocaleDateString()}</td><td>{x.person}</td><td>{x.vendor}</td><td>{x.category}</td><td><strong>${x.amount.toFixed(2)}</strong></td><td><span className={`table-status ${x.status==="matched"?"matched":"review"}`}>{x.status==="matched"?<CheckCircle2 size={15}/>:<AlertCircle size={15}/>} {x.status}</span></td><td><button className="text-button" onClick={()=>view(x)}><Eye size={16}/> Review</button></td></tr>)}</tbody></table></div></section>
    {selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><section className="receipt-modal" onClick={e=>e.stopPropagation()}><button className="icon-button modal-close" onClick={()=>setSelected(null)}><X/></button><div><p className="eyebrow">Full receipt entry</p><h2>{selected.vendor}</h2><dl className="receipt-details"><div><dt>Employee</dt><dd>{selected.person}</dd></div><div><dt>Purchase date</dt><dd>{new Date(selected.purchaseDate+"T12:00:00").toLocaleDateString()}</dd></div><div><dt>Amount</dt><dd>${selected.amount.toFixed(2)}</dd></div><div><dt>Category</dt><dd>{selected.category}</dd></div><div><dt>Business purpose</dt><dd>{selected.purpose}</dd></div><div><dt>Status</dt><dd>{selected.status.replaceAll("_"," ")}</dd></div><div><dt>Acknowledged</dt><dd>{selected.acknowledgedAt?new Date(selected.acknowledgedAt).toLocaleString():"Not yet"}</dd></div></dl><label>Review notes<textarea rows={4} value={reviewNotes} onChange={e=>setReviewNotes(e.target.value)} placeholder="Optional note for this receipt"/></label><div className="receipt-actions"><button className="button secondary" onClick={()=>decide("needs_review")}>Acknowledge</button><button className="button secondary danger" onClick={()=>decide("rejected")}>Reject</button><button className="button primary" onClick={()=>decide("matched")}>Approve</button></div></div><div className="receipt-preview">{fileUrl?(selected.storagePath.toLowerCase().endsWith(".pdf")?<iframe src={fileUrl} title="Receipt PDF"/>:<img src={fileUrl} alt={`Receipt from ${selected.vendor}`}/>):<p>Preparing receipt image…</p>}</div></section></div>}
  </div>}
