import { FormEvent, useEffect, useMemo, useState } from "react";
import { Minus, Package, Plus, ShoppingCart, X } from "lucide-react";
import { supabase } from "../lib/supabase";
import type { CatalogCategory, CatalogItem, Profile } from "../types";
type Store={id:string;name:string};
type Line={key:string;item:CatalogItem;size:string|null;quantity:number};
type History={id:string;total:number;decision:string|null;decision_notes:string|null;created_at:string;employee_name:string|null;stores?:{name:string}|null};

export default function Uniforms({profile,category="uniform"}:{profile:Profile;category?:CatalogCategory}){
 const [items,setItems]=useState<CatalogItem[]>([]),[stores,setStores]=useState<Store[]>([]),[history,setHistory]=useState<History[]>([]),[cart,setCart]=useState<Line[]>([]);
 const [selectedSizes,setSelectedSizes]=useState<Record<string,string>>({}),[selectedQty,setSelectedQty]=useState<Record<string,number>>({}),[cartOpen,setCartOpen]=useState(false),[storeId,setStoreId]=useState(""),[employeeName,setEmployeeName]=useState(""),[ack,setAck]=useState(false),[notes,setNotes]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const load=async()=>{if(!supabase)return;const[c,s,o]=await Promise.all([supabase.from("catalog_items").select("*").eq("category",category).eq("active",true).order("name"),supabase.from("stores").select("id,name").eq("active",true).order("name"),supabase.from("portal_orders").select("id,total,decision,decision_notes,created_at,employee_name,stores(name)").eq("ordered_by",profile.id).eq("category",category).order("created_at",{ascending:false})]);setItems((c.data??[]).map((x:any)=>({id:x.id,category:x.category,name:x.name,description:x.description,price:Number(x.price),imagePath:x.image_path,imageUrl:x.image_path?supabase!.storage.from("catalog-images").getPublicUrl(x.image_path).data.publicUrl:null,sizes:x.sizes??[],active:x.active})));setStores(s.data??[]);setHistory((o.data??[])as any);if(!storeId&&s.data?.length)setStoreId(s.data[0].id)};
 useEffect(()=>{load()},[category]);
 const count=cart.reduce((n,l)=>n+l.quantity,0),total=useMemo(()=>cart.reduce((n,l)=>n+l.item.price*l.quantity,0),[cart]);
 const setPickerQty=(id:string,n:number)=>setSelectedQty(q=>({...q,[id]:Math.max(1,(q[id]??1)+n)}));
 const addToCart=(item:CatalogItem)=>{const size=item.sizes.length?(selectedSizes[item.id]??item.sizes[0]):null,quantity=selectedQty[item.id]??1,key=`${item.id}:${size??"default"}`;setCart(lines=>{const found=lines.find(l=>l.key===key);return found?lines.map(l=>l.key===key?{...l,quantity:l.quantity+quantity}:l):[...lines,{key,item,size,quantity}]});setSelectedQty(q=>({...q,[item.id]:1}));setMessage(`${item.name}${size?` (${size})`:""} added to cart.`)};
 const adjustCart=(key:string,n:number)=>setCart(lines=>lines.map(l=>l.key===key?{...l,quantity:l.quantity+n}:l).filter(l=>l.quantity>0));
 const submit=async(e:FormEvent)=>{e.preventDefault();if(!supabase||!storeId)return;setBusy(true);setMessage("");const responsibility=category==="uniform"?"employee_deduction":"store_purchase";const{data:order,error}=await supabase.from("portal_orders").insert({ordered_by:profile.id,responsibility,employee_id:responsibility==="employee_deduction"?profile.id:null,employee_name:category==="uniform"?employeeName:null,store_id:storeId,store_name:stores.find(s=>s.id===storeId)?.name??"Store",category,notes,total,payroll_acknowledged:category==="uniform"?ack:false}).select("id").single();if(error||!order){setMessage(error?.message??"Order could not be saved.");setBusy(false);return}const{error:ie}=await supabase.from("portal_order_items").insert(cart.map(l=>({order_id:order.id,catalog_item_id:l.item.id,item_name:l.item.name,unit_price:l.item.price,quantity:l.quantity,size:l.size})));setBusy(false);if(ie){setMessage(ie.message);return}setCart([]);setEmployeeName("");setAck(false);setNotes("");setCartOpen(false);setMessage("Order submitted and added to your submission history.");load()};
 const label=category==="uniform"?"Uniforms":"Smallwares";
 return <div className="page"><div className="page-heading heading-with-action"><div><p className="eyebrow">{label}</p><h1>{label} catalog.</h1><p>Select a size and quantity, add it to the cart, then repeat for any additional sizes.</p></div><button className="button primary" onClick={()=>setCartOpen(true)} disabled={!count}><ShoppingCart/> Review cart ({count})</button></div>{message&&<p className="inline-message">{message}</p>}
 <section className="panel catalog-grid">{items.map(item=><article className="catalog-card" key={item.id}><div className="catalog-image">{item.imageUrl?<img src={item.imageUrl} alt={item.name}/>:<Package/>}</div><div className="catalog-copy"><h2>{item.name}</h2><p>{item.description}</p><strong>${item.price.toFixed(2)}</strong></div>{item.sizes.length>0&&<label>Size<select value={selectedSizes[item.id]??item.sizes[0]} onChange={e=>setSelectedSizes(v=>({...v,[item.id]:e.target.value}))}>{item.sizes.map(s=><option key={s}>{s}</option>)}</select></label>}<label>Quantity<div className="stepper"><button type="button" onClick={()=>setPickerQty(item.id,-1)}><Minus/></button><span>{selectedQty[item.id]??1}</span><button type="button" onClick={()=>setPickerQty(item.id,1)}><Plus/></button></div></label><button className="button secondary full" type="button" onClick={()=>addToCart(item)}><ShoppingCart/> Add to cart</button></article>)}</section>
 <section className="panel submission-history"><h2>My {label.toLowerCase()} submissions</h2>{history.length===0?<p>No submissions yet.</p>:history.map(x=><article key={x.id}><div><strong>${Number(x.total).toFixed(2)} · {x.stores?.name??"Store"}</strong><small>{new Date(x.created_at).toLocaleString()}{x.employee_name?` · ${x.employee_name}`:""}</small></div><span className={`decision-pill ${x.decision??"pending"}`}>{(x.decision??"pending review").replaceAll("_"," ")}</span>{x.decision_notes&&<p><strong>Reviewer note:</strong> {x.decision_notes}</p>}</article>)}</section>
 {cartOpen&&<div className="modal-backdrop" onClick={()=>setCartOpen(false)}><form className="cart-modal" onSubmit={submit} onClick={e=>e.stopPropagation()}><button className="icon-button modal-close" type="button" onClick={()=>setCartOpen(false)}><X/></button><p className="eyebrow">Final review</p><h2>Your cart</h2><div className="cart-lines">{cart.map(l=><div key={l.key}><div><strong>{l.item.name}</strong><small>{l.size||"Standard"} · ${l.item.price.toFixed(2)} each</small></div><div className="stepper"><button type="button" onClick={()=>adjustCart(l.key,-1)}><Minus/></button><span>{l.quantity}</span><button type="button" onClick={()=>adjustCart(l.key,1)}><Plus/></button></div><strong>${(l.item.price*l.quantity).toFixed(2)}</strong></div>)}</div><div className="cart-total"><span>Total</span><strong>${total.toFixed(2)}</strong></div><label>Store<select required value={storeId} onChange={e=>setStoreId(e.target.value)}><option value="">Select a store</option>{stores.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label>{category==="uniform"&&<><label>Employee’s full payroll name<input required value={employeeName} onChange={e=>setEmployeeName(e.target.value)}/></label><label className="check-row"><input type="checkbox" required checked={ack} onChange={e=>setAck(e.target.checked)}/><span>The above-named employee acknowledges that the total amount for these uniforms will be automatically deducted from their payroll check.</span></label></>}<label>Request notes<textarea rows={3} value={notes} onChange={e=>setNotes(e.target.value)}/></label><button className="button primary full" disabled={!cart.length||busy||!storeId||(category==="uniform"&&(!employeeName.trim()||!ack))}>{busy?"Submitting…":`Submit ${label.toLowerCase()} order`}</button></form></div>}</div>;
}
